name: Azure-pipeline

on:
    push:
        branches:
            - main

jobs:
  call-azure-pipeline-workflow:
    uses: ./.github/workflows/azure-pipeline.yml

  azure-deployment:
        needs: call-azure-pipeline-workflow
        runs-on: ubuntu-latest
        environment: Azure-IaC
        defaults:
            run:
               working-directory: ./

        steps:
           - name: Syntax validation
             uses: actions/checkout@v4

           - name: Terraform validation
             uses: hashicorp/setup-terraform@v3
             with:
               terraform_version: 1.6.0
            
           - name: Init
             run: terraform init
             
           - name: Validation
             run: terraform validate

           - name: Planning
             run: terraform plan

           - name: Applying
             run: terraform apply -auto-approve tfplan

