name: Azure-pipeline

on:
    push:
        branches:
            - main
    

jobs:
  
  azure-deployment:
        runs-on: ubuntu-latest
        environment: Azure-IaC
        defaults:
            run:
               working-directory: ./

        steps:
           - name: Syntax validation
             uses: actions/checkout@v4

           - name: Terraform validation
             uses: hashicorp/setup-terraform@v3
             with:
               terraform_version: 1.6.0
            
           - name: Init
             run: terraform init
             
           - name: Validation
             run: terraform validate

           - name: Decode tfvars file from secret
             run: echo "${{ TERRAFORM_TFVARS_BASE64 }}" | base64 -d > terraform.tfvars

           - name: Plan
             run: terraform plan -var-file="terraform.tfvars"

           - name: Applying
             run: terraform apply -auto-approve tfplan

