name: Azure-pipeline

on:
    push:
        branches:
            - main
    

jobs:
  
  azure-deployment:
        runs-on: ubuntu-latest
        environment: Azure-IaC
        defaults:
            run:
               working-directory: ./
  

        steps:
           - name: Syntax validation
             uses: actions/checkout@v4

           - name: Terraform validation
             uses: hashicorp/setup-terraform@v3
             with:
               terraform_version: 1.6.0

           - name: Set Terraform environment variables
             run: echo "Terraform env vars set"
             env:
              ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
              ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
              ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
              ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}



           - name: Create tfvars from GitHub secrets
             run: |
              echo "client_id = \"$ARM_CLIENT_ID\"" > terraform.tfvars
              echo "client_secret = \"$ARM_CLIENT_SECRET\"" >> terraform.tfvars
              echo "subscription_id = \"$ARM_SUBSCRIPTION_ID\"" >> terraform.tfvars
              echo "tenant_id = \"$ARM_TENANT_ID\"" >> terraform.tfvars   

              
           - name: Init
             run: terraform init

           - name: Validation
             run: terraform validate

           - name: Decode tfvars file from secret
             env: 
              TFVARS_BASE64: ${{ secrets.TERRAFORM_TFVARS_BASE64 }}
             run: 
               echo "$TFVARS_BASE64" | base64 -d > terraform.tfvars

           - name: Plan
             run: terraform plan -var-file="terraform.tfvars"

           - name: Applying
             run: terraform apply -auto-approve

