name: Azure-pipeline

on:
    push:
        branches:
            - main
    

jobs:
  
  azure-deployment:
        runs-on: ubuntu-latest
        environment: Azure-IaC
        defaults:
            run:
               working-directory: ./

        env:
              ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
              ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
              ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
              ARM_SECRET_ID: ${{secrets.AZURE_SECRET_ID}}

        steps:
           - name: Syntax validation
             uses: actions/checkout@v4

           - name: Terraform validation
             uses: hashicorp/setup-terraform@v3
             with:
               terraform_version: 1.6.0

           - name: Init
             run: terraform init

           - name: Login 
             uses: az login

           - name: Validation
             run: terraform validate

           - name: Decode tfvars file from secret
             env: 
              TFVARS_BASE64: ${{ secrets.TERRAFORM_TFVARS_BASE64 }}
             run: 
               echo "$TFVARS_BASE64" | base64 -d > terraform.tfvars

           - name: Plan
             run: terraform plan -var-file="terraform.tfvars"

           - name: Applying
             run: terraform apply -auto-approve

